# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apps.emqx.io_emqxes.yaml
- bases/apps.emqx.io_rebalances.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
- path: ./compat/v2beta1_patch.yaml
  target:
    kind: CustomResourceDefinition
    name: emqxes.apps.emqx.io
